import type { Label } from "../types";

export const labels: Label[] = [
    {
      "id": 97,
      "index": 0,
      "prop": 0,
      "typeText": "u",
      "numText": '1',
      "type": "circle",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [],
      "secStart": true,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 2,
      "isLabel": true,
      "secLength": 36,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 98,
      "index": 1,
      "prop": 0,
      "typeText": "u",
      "numText": '2',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [],
      "secStart": true,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": false,
      "arrowIn": false,
      "level": 1,
      "isLabel": true,
      "secLength": 36,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": false,
      "percent": 50,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 99,
      "index": 2,
      "prop": 0,
      "typeText": "u",
      "numText": '3',
      "type": "roundrect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 101,
      "index": 3,
      "prop": 0,
      "typeText": "u",
      "numText": '4',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        99
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 102,
      "index": 4,
      "prop": 0,
      "typeText": "u",
      "numText": '5',
      "type": "rect",
      "num": 1,
      "score": -1,
      "isBase": true,
      "connections": [
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": false,
      "percent": 0,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 103,
      "index": 5,
      "prop": 0,
      "typeText": "u",
      "numText": '6',
      "type": "rect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        97
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        90
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t1",
      "drawAnyCase": false
    },
    {
      "id": 104,
      "index": 6,
      "prop": 0,
      "typeText": "u",
      "numText": '7',
      "type": "circle",
      "num": 1,
      "score": 1,
      "isBase": false,
      "connections": [
        98
      ],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        91
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t2",
      "drawAnyCase": false
    },
    {
      "id": 105,
      "index": 7,
      "prop": 0,
      "typeText": "u",
      "numText": '8',
      "type": "roundrect",
      "num": 1,
      "score": 0.3999999999999999,
      "isBase": true,
      "connections": [
        104
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        91
      ],
      "grey": false,
      "percent": 70,
      "sectorName": "t2",
      "drawAnyCase": false
    },
    {
      "id": 106,
      "index": 8,
      "prop": 0,
      "typeText": "u",
      "numText": '9',
      "type": "roundrect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        104,
        105
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        91
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t2",
      "drawAnyCase": false
    },
    {
      "id": 107,
      "index": 9,
      "prop": 0,
      "typeText": "u",
      "numText": '10',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        104,
        105,
        106
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        91
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t2",
      "drawAnyCase": false
    },
    {
      "id": 108,
      "index": 10,
      "prop": 0,
      "typeText": "u",
      "numText": '11',
      "type": "rect",
      "num": 1,
      "score": 0.55,
      "isBase": true,
      "connections": [
        101
      ],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        92
      ],
      "grey": false,
      "percent": 77.5,
      "sectorName": "t3",
      "drawAnyCase": false
    },
    {
      "id": 109,
      "index": 11,
      "prop": 0,
      "typeText": "u",
      "numText": '12',
      "type": "roundrect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        105
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": false,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        92
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t3",
      "drawAnyCase": false
    },
    {
      "id": 110,
      "index": 12,
      "prop": 0,
      "typeText": "u",
      "numText": '13',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        109
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        92
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t3",
      "drawAnyCase": false
    },
    {
      "id": 111,
      "index": 13,
      "prop": 0,
      "typeText": "u",
      "numText": '14',
      "type": "circle",
      "num": 1,
      "score": 0.5,
      "isBase": true,
      "connections": [
        108
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        92
      ],
      "grey": false,
      "percent": 75,
      "sectorName": "t3",
      "drawAnyCase": false
    },
    {
      "id": 112,
      "index": 14,
      "prop": 0,
      "typeText": "u",
      "numText": '15',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        108
      ],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 113,
      "index": 15,
      "prop": 0,
      "typeText": "u",
      "numText": '16',
      "type": "roundrect",
      "num": 1,
      "score": -1,
      "isBase": true,
      "connections": [
        112
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": false,
      "percent": 0,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 114,
      "index": 16,
      "prop": 0,
      "typeText": "u",
      "numText": '17',
      "type": "circle",
      "num": 1,
      "score": 0,
      "isBase": false,
      "connections": [
        113
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": false,
      "percent": 50,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 115,
      "index": 17,
      "prop": 0,
      "typeText": "u",
      "numText": '18',
      "type": "circle",
      "num": 1,
      "score": -1,
      "isBase": false,
      "connections": [
        114
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": false,
      "percent": 0,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 116,
      "index": 18,
      "prop": 0,
      "typeText": "u",
      "numText": '19',
      "type": "roundrect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        114,
        115
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 117,
      "index": 19,
      "prop": 0,
      "typeText": "u",
      "numText": '20',
      "type": "circle",
      "num": 1,
      "score": 0,
      "isBase": false,
      "connections": [
        116
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        93
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t4",
      "drawAnyCase": false
    },
    {
      "id": 118,
      "index": 20,
      "prop": 0,
      "typeText": "u",
      "numText": '21',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        101
      ],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        94
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t5",
      "drawAnyCase": false
    },
    {
      "id": 119,
      "index": 21,
      "prop": 0,
      "typeText": "u",
      "numText": '22',
      "type": "rect",
      "num": 1,
      "score": 0.1,
      "isBase": true,
      "connections": [
        118
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        94
      ],
      "grey": false,
      "percent": 55,
      "sectorName": "t5",
      "drawAnyCase": false
    },
    {
      "id": 120,
      "index": 22,
      "prop": 0,
      "typeText": "u",
      "numText": '23',
      "type": "roundrect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        119
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        94
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t5",
      "drawAnyCase": false
    },
    {
      "id": 121,
      "index": 23,
      "prop": 0,
      "typeText": "u",
      "numText": '24',
      "type": "circle",
      "num": 1,
      "score": 0,
      "isBase": false,
      "connections": [
        119,
        120
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        94
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t5",
      "drawAnyCase": false
    },
    {
      "id": 122,
      "index": 24,
      "prop": 0,
      "typeText": "u",
      "numText": '25',
      "type": "circle",
      "num": 1,
      "score": 0.8,
      "isBase": true,
      "connections": [],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": false,
      "percent": 90,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 123,
      "index": 25,
      "prop": 0,
      "typeText": "u",
      "numText": '26',
      "type": "rect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        101
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 124,
      "index": 26,
      "prop": 0,
      "typeText": "u",
      "numText": '27',
      "type": "rect",
      "num": 1,
      "score": 1,
      "isBase": true,
      "connections": [
        123
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 125,
      "index": 27,
      "prop": 0,
      "typeText": "u",
      "numText": '28',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        105,
        106
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 126,
      "index": 28,
      "prop": 0,
      "typeText": "u",
      "numText": '29',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        124
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 127,
      "index": 29,
      "prop": 0,
      "typeText": "u",
      "numText": '30',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        124,
        126
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": false,
      "percent": 50,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 128,
      "index": 30,
      "prop": 0,
      "typeText": "u",
      "numText": '31',
      "type": "circle",
      "num": 1,
      "score": 1,
      "isBase": false,
      "connections": [
        124,
        126
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": false,
      "percent": 100,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 129,
      "index": 31,
      "prop": 0,
      "typeText": "u",
      "numText": '32',
      "type": "circle",
      "num": 1,
      "score": 0,
      "isBase": false,
      "connections": [
        124,
        126
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 130,
      "index": 32,
      "prop": 0,
      "typeText": "u",
      "numText": '33',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        124,
        99
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 135,
      "index": 33,
      "prop": 0,
      "typeText": "u",
      "numText": '34',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        123,
        125,
        126,
        127,
        130
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        95
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t6",
      "drawAnyCase": false
    },
    {
      "id": 131,
      "index": 34,
      "prop": 0,
      "typeText": "u",
      "numText": '35',
      "type": "circle",
      "num": 1,
      "score": 0.6000000000000001,
      "isBase": false,
      "connections": [],
      "secStart": true,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        96
      ],
      "grey": false,
      "percent": 80,
      "sectorName": "t7",
      "drawAnyCase": false
    },
    {
      "id": 132,
      "index": 35,
      "prop": 0,
      "typeText": "u",
      "numText": '36',
      "type": "circle",
      "num": 1,
      "score": 0.6,
      "isBase": false,
      "connections": [
        131
      ],
      "secStart": false,
      "secEnd": false,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        96
      ],
      "grey": false,
      "percent": 80,
      "sectorName": "t7",
      "drawAnyCase": false
    },
    {
      "id": 133,
      "index": 36,
      "prop": 0,
      "typeText": "u",
      "numText": '37',
      "type": "circle",
      "num": 1,
      "score": 0,
      "isBase": false,
      "connections": [
        132
      ],
      "secStart": false,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": true,
      "arrowIn": false,
      "level": 0,
      "isLabel": true,
      "secLength": 1,
      "lowLevel": [],
      "highLevel": [
        96
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t7",
      "drawAnyCase": false
    },
    {
      "id": 134,
      "index": 37,
      "prop": 0,
      "typeText": "u",
      "numText": '38',
      "type": "roundrect",
      "num": 1,
      "score": 0,
      "isBase": true,
      "connections": [
        131,
        132,
        133
      ],
      "secStart": true,
      "secEnd": true,
      "fontStyle": "normal",
      "arrowOut": false,
      "arrowIn": true,
      "level": 0,
      "isLabel": true,
      "secLength": 36,
      "lowLevel": [],
      "highLevel": [
        96
      ],
      "grey": true,
      "percent": 0,
      "sectorName": "t7",
      "drawAnyCase": false
    }
  ]