export const labels = [
    {
        id: 0,
        prop: '1',
        typeText: 'd',
        numText: '2.4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 1,
        lowLevel: [11], //элементы в иерархии ниже
        highLevel: [], //элементы в иерархии выше
    },
    {
        id: 1,
        prop: '1',
        typeText: 'd',
        numText: '3.2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 3,
        lowLevel: [12, 13],
        highLevel: [],
    },
    {
        id: 2,
        prop: '1',
        typeText: 'd',
        numText: '3.3',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 2,
        lowLevel: [14],
        highLevel: [],
    },
    {
        id: 3,
        prop: '1',
        typeText: 'd',
        numText: '3.4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 3,
        lowLevel: [15],
        highLevel: [],
    },
    {
        id: 4,
        prop: '1',
        typeText: 'd',
        numText: '3.5',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 3,
        lowLevel: [16, 17],
        highLevel: [],
    },
    {
        id: 5,
        prop: '1',
        typeText: 'd',
        numText: '3.7',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 1,
        lowLevel: [18],
        highLevel: [],
    },
    {
        id: 6,
        prop: '1',
        typeText: 'd',
        numText: '3.8',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 5,
        lowLevel: [19, 20],
        highLevel: [],
    },
    {
        id: 7,
        prop: '1',
        typeText: 'd',
        numText: '4.2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 3,
        lowLevel: [21, 22],
        highLevel: [],
    },
    {
        id: 8,
        prop: '2',
        typeText: 'Ψ',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 1,
        lowLevel: [23],
        highLevel: [],
    },
    {
        id: 9,
        prop: '3',
        typeText: 'S',
        numText: '5',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 1,
        lowLevel: [24],
        highLevel: [],
    },
    {
        id: 10,
        prop: '3',
        typeText: 'S',
        numText: '3',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 2,
        isLabel: false,
        secLength: 4,
        lowLevel: [25, 26],
        highLevel: [],
    },
    //---------------------------------------------//
    //
    //
    //---------------------------------------------//
    {
        id: 11,
        prop: '1',
        typeText: 't',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 1,
        lowLevel: [27],
        highLevel: [0],
    },
    {
        id: 12,
        prop: '1',
        typeText: 't',
        numText: '5',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 1,
        lowLevel: [28],
        highLevel: [1],
    },
    {
        id: 13,
        prop: '1',
        typeText: 't',
        numText: '7',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 2,
        lowLevel: [29, 30],
        highLevel: [1],
    },
    {
        id: 14,
        prop: '1',
        typeText: 't',
        numText: '8',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 2,
        lowLevel: [31, 32],
        highLevel: [2],
    },
    {
        id: 15,
        prop: '1',
        typeText: 't',
        numText: '12',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 3,
        lowLevel: [33, 34, 35],
        highLevel: [3],
    },
    {
        id: 16,
        prop: '1',
        typeText: 't',
        numText: '14',
        type: 'rect',
        num: 1,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 1,
        lowLevel: [36],
        highLevel: [4],
    },
    {
        id: 17,
        prop: '1',
        typeText: 't',
        numText: '15',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 2,
        lowLevel: [37, 38],
        highLevel: [4],
    },
    {
        id: 18,
        prop: '1',
        typeText: 't',
        numText: '20',
        type: 'rect',
        num: 1,
        score: 0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 1,
        lowLevel: [39],
        highLevel: [5],
    },
    {
        id: 19,
        prop: '1',
        typeText: 't',
        numText: '21',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 2,
        lowLevel: [40, 41],
        highLevel: [6],
    },
    {
        id: 20,
        prop: '1',
        typeText: 't',
        numText: '22',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 3,
        lowLevel: [42, 43, 44],
        highLevel: [6],
    },
    {
        id: 21,
        prop: '1',
        typeText: 't',
        numText: '22',
        type: 'rect',
        num: 1,
        score: -0.7,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 2,
        lowLevel: [45, 46],
        highLevel: [7],
    },
    {
        id: 22,
        prop: '1',
        typeText: 't',
        numText: '22',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: true,
        secLength: 1,
        lowLevel: [47],
        highLevel: [7],
    },
    {
        id: 23,
        prop: '2',
        typeText: 'Ψ',
        numText: '2.2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: false,
        secLength: 1,
        lowLevel: [48],
        highLevel: [8],
    },
    {
        id: 24,
        prop: '3',
        typeText: 'S',
        numText: '5.1',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: false,
        secLength: 1,
        lowLevel: [49],
        highLevel: [9],
    },
    {
        id: 25,
        prop: '3',
        typeText: 'S',
        numText: '3.2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: false,
        secLength: 2,
        lowLevel: [50, 51],
        highLevel: [10],
    },
    {
        id: 26,
        prop: '3',
        typeText: 'S',
        numText: '3.1',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: false,
        arrowIn: false,
        level: 1,
        isLabel: false,
        secLength: 2,
        lowLevel: [52, 53],
        highLevel: [10],
    },
    //---------------------------------------------//
    //
    //
    //---------------------------------------------//
    {
        id: 27,
        prop: '1',
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [11],
        index: 0,
    },
    {
        id: 28,
        prop: '1',
        typeText: 'u',
        numText: '6',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [29, 50, 53],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [12],
    },
    {
        id: 29,
        prop: '1',
        typeText: 'u',
        numText: '11',
        type: 'roundrect',
        num: 1,
        score: -0.8,
        mtxPos: '',
        isBase: true,
        connections: [30, 31, 48, 52],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [13],
    },
    {
        id: 30,
        prop: '1',
        typeText: 'u',
        numText: '12',
        type: 'rect',
        num: 1,
        score: -0.5,
        mtxPos: '',
        isBase: true,
        connections: [34, 52],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [13],
    },
    {
        id: 31,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [32],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [14],
    },
    {
        id: 32,
        prop: '1',
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [34, 49],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [14],
    },
    {
        id: 33,
        prop: '1',
        typeText: 'u',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [27],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [15],
    },
    {
        id: 34,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'rect',
        num: 1,
        score: -0.8,
        mtxPos: '',
        isBase: true,
        connections: [35, 52],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [15],
    },
    {
        prop: '1',
        id: 35,
        typeText: 'u',
        numText: '5',
        type: 'roundrect',
        num: 1,
        score: -0.5,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [15],
    },
    {
        id: 36,
        prop: '1',
        typeText: 'u',
        numText: '2',
        type: 'rect',
        num: 1,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [16],
    },
    {
        id: 37,
        prop: '1',
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [38],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [17],
    },
    {
        id: 38,
        prop: '1',
        typeText: 'u',
        numText: '5',
        type: 'rect',
        num: 1,
        score: -0.5,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [17],
    },
    {
        id: 39,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'roundrect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [40, 47, 50],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [18],
    },
    {
        id: 40,
        prop: '1',
        typeText: 'u',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [48],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [19],
    },
    {
        id: 41,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'roundrect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [43],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [19],
    },
    {
        id: 42,
        prop: '1',
        typeText: 'u',
        numText: '2',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [43, 44, 45, 47],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [20],
    },
    {
        id: 43,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'rect',
        num: 1,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [44],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [20],
    },
    {
        id: 44,
        prop: '1',
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: -0.2,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [51],
        highLevel: [20],
    },
    {
        id: 45,
        prop: '1',
        typeText: 'u',
        numText: '3',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [48],
        highLevel: [21],
    },
    {
        id: 46,
        prop: '1',
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [49, 51],
        highLevel: [21],
    },
    {
        id: 47,
        prop: '1',
        typeText: 'u',
        numText: '6',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [22],
    },
    {
        id: 48,
        prop: '2',
        typeText: 'Ψ',
        numText: '6',
        type: 'rect',
        num: 1,
        score: 1,
        mtxPos: '',
        isBase: true,
        connections: [50],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [23],
    },
    {
        id: 49,
        prop: '3',
        typeText: 'pk',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [24],
    },
    {
        id: 50,
        prop: '3',
        typeText: 'ok',
        numText: '3',
        type: 'circle',
        num: 1,
        score: 0.4,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [25],
    },
    {
        id: 51,
        prop: '3',
        typeText: 'uk',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [25],
    },
    {
        id: 52,
        prop: '3',
        typeText: 'uk',
        numText: '1',
        type: 'rect',
        num: 1,
        score: 1,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [26],
    },
    {
        id: 53,
        prop: '3',
        typeText: 'pk',
        numText: '7',
        type: 'rect',
        num: 1,
        score: 1,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel: [],
        highLevel: [26],
    },
    /*
    {
        id: 0,
        typeText: 'u',
        numText: '1',
        type: 'circle',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [1, 2, 3, 4, 5, 18], //элементы, опирающиеся на данный
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0, //уровень отрисовки
        isLabel: true, //необходимость в фигуре
        secLength: 1, // длина в элементах
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 1,
        typeText: 'u',
        numText: '2',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [3, 4],
        secStart: false,
        secEnd: false,
        fontStyle: 'italic',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 2,
        typeText: 'u',
        numText: '3',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: false,
        connections: [],
        secStart: false,
        secEnd: false,
        fontStyle: 'bold',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 3,
        typeText: 'u',
        numText: '4',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: false,
        connections: [],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 4,
        typeText: 'u',
        numText: '5',
        type: 'circle',
        num: 2,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 5,
        typeText: 'u',
        numText: '6',
        type: 'rect',
        num: 3,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [7, 8],
        secStart: true,
        secEnd: false,
        fontStyle: 'italic',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 6,
        typeText: 'u',
        numText: '7',
        type: 'rect',
        num: 1,
        score: 0.4,
        mtxPos: '',
        isBase: true,
        connections: [8, 9],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 7,
        typeText: 'u',
        numText: '8',
        type: 'circle',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: false,
        fontStyle: 'bold',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 8,
        typeText: 'u',
        numText: '9',
        type: 'roundrect',
        num: 2,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 9,
        typeText: 'u',
        numText: '10',
        type: 'rect',
        num: 1,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [10, 11, 12, 16],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },

    {
        id: 10,
        typeText: 'u',
        numText: '11',
        type: 'rect',
        num: 1,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [11],
        secStart: false,
        secEnd: false,
        fontStyle: 'italic',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 11,
        typeText: 'u',
        numText: '12',
        type: 'circle',
        num: 3,
        score: -1,
        mtxPos: '',
        isBase: true,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'bold',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 12,
        typeText: 'u',
        numText: '13',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [13, 14, 15, 17],
        secStart: true,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 13,
        typeText: 'u',
        numText: '14',
        type: 'circle',
        num: 1,
        score: 1,
        mtxPos: '',
        isBase: true,
        connections: [15],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 14,
        typeText: 'u',
        numText: '15',
        type: 'circle',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [15],
        secStart: false,
        secEnd: false,
        fontStyle: 'italic',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 15,
        typeText: 'u',
        numText: '16',
        type: 'rect',
        num: 2,
        score: 0,
        mtxPos: '',
        isBase: false,
        connections: [],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 16,
        typeText: 'u',
        numText: '17',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [17],
        secStart: false,
        secEnd: false,
        fontStyle: 'bold',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 17,
        typeText: 'u',
        numText: '18',
        type: 'rect',
        num: 2,
        score: 0,
        mtxPos: '',
        isBase: true,
        connections: [18],
        secStart: false,
        secEnd: false,
        fontStyle: 'normal',
        arrowOut: true,
        arrowIn: false,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },
    {
        id: 18,
        typeText: 'u',
        numText: '19',
        type: 'rect',
        num: 1,
        score: 0,
        mtxPos: '',
        isBase: false,
        connections: [],
        secStart: false,
        secEnd: true,
        fontStyle: 'normal',
        arrowOut: false,
        arrowIn: true,
        level: 0,
        isLabel: true,
        secLength: 1,
        lowLevel:[],
        highLevel:[],
    },*/
]
