import type { Label } from "../../types";

export const oneLevelCMKD1: Label[] = [
  {
    id: 99,
    prop: 0,
    typeText: "u",
    numText: "3",
    type: "roundrect",
    num: 3,
    score: -1,
    isBase: true,
    connections: [],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t1",
  },
  {
    id: 101,
    prop: 0,
    typeText: "u",
    numText: "4",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [99],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: true,
    sectorName: "t1",
  },
  {
    id: 102,
    prop: 0,
    typeText: "u",
    numText: "5",
    type: "rect",
    num: 1,
    score: -1,
    isBase: true,
    connections: [],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t1",
  },
  {
    id: 103,
    prop: 0,
    typeText: "u",
    numText: "6",
    type: "rect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [97],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: true,
    sectorName: "t1",
  },
  {
    id: 104,
    prop: 0,
    typeText: "u",
    numText: "7",
    type: "circle",
    num: 1,
    score: 1,
    isBase: false,
    connections: [98],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t2",
  },
  {
    id: 105,
    prop: 0,
    typeText: "u",
    numText: "8",
    type: "roundrect",
    num: 1,
    score: 0.3999999999999999,
    isBase: true,
    connections: [104],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t2",
  },
  {
    id: 106,
    prop: 0,
    typeText: "u",
    numText: "9",
    type: "roundrect",
    num: 1,
    score: 1,
    isBase: true,
    connections: [104, 105],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t2",
  },
  {
    id: 107,
    prop: 0,
    typeText: "u",
    numText: "10",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [104, 105, 106],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: true,
    sectorName: "t2",
  },
  {
    id: 108,
    prop: 0,
    typeText: "u",
    numText: "11",
    type: "rect",
    num: 1,
    score: 0.55,
    isBase: true,
    connections: [101],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t3",
  },
  {
    id: 109,
    prop: 0,
    typeText: "u",
    numText: "12",
    type: "roundrect",
    num: 1,
    score: 1,
    isBase: true,
    connections: [105],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: false,
    secLength: 1,
    grey: false,
    sectorName: "t3",
  },
  {
    id: 110,
    prop: 0,
    typeText: "u",
    numText: "13",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [109],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t3",
  },
  {
    id: 111,
    prop: 0,
    typeText: "u",
    numText: "14",
    type: "circle",
    num: 1,
    score: 0.5,
    isBase: true,
    connections: [108],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t3",
  },
  {
    id: 112,
    prop: 0,
    typeText: "u",
    numText: "15",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [108],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t4",
  },
  {
    id: 113,
    prop: 0,
    typeText: "u",
    numText: "16",
    type: "roundrect",
    num: 1,
    score: -1,
    isBase: true,
    connections: [112],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t4",
  },
  {
    id: 114,
    prop: 0,
    typeText: "u",
    numText: "17",
    type: "circle",
    num: 1,
    score: 0,
    isBase: false,
    connections: [113],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t4",
  },
  {
    id: 115,
    prop: 0,
    typeText: "u",
    numText: "18",
    type: "circle",
    num: 1,
    score: -1,
    isBase: false,
    connections: [114],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t4",
  },
  {
    id: 116,
    prop: 0,
    typeText: "u",
    numText: "19",
    type: "roundrect",
    num: 1,
    score: 1,
    isBase: true,
    connections: [114, 115],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t4",
  },
  {
    id: 117,
    prop: 0,
    typeText: "u",
    numText: "20",
    type: "circle",
    num: 1,
    score: 0,
    isBase: false,
    connections: [116],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t4",
  },
  {
    id: 118,
    prop: 0,
    typeText: "u",
    numText: "21",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [101],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t5",
  },
  {
    id: 119,
    prop: 0,
    typeText: "u",
    numText: "22",
    type: "rect",
    num: 1,
    score: 0.1,
    isBase: true,
    connections: [118],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t5",
  },
  {
    id: 120,
    prop: 0,
    typeText: "u",
    numText: "23",
    type: "roundrect",
    num: 1,
    score: 1,
    isBase: true,
    connections: [119],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t5",
  },
  {
    id: 121,
    prop: 0,
    typeText: "u",
    numText: "24",
    type: "circle",
    num: 1,
    score: 0,
    isBase: false,
    connections: [119, 120],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t5",
  },
  {
    id: 122,
    prop: 0,
    typeText: "u",
    numText: "25",
    type: "circle",
    num: 1,
    score: 0.8,
    isBase: true,
    connections: [],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t6",
  },
  {
    id: 123,
    prop: 0,
    typeText: "u",
    numText: "26",
    type: "rect",
    num: 1,
    score: -1,
    isBase: true,
    connections: [101],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t6",
  },
  {
    id: 124,
    prop: 0,
    typeText: "u",
    numText: "27",
    type: "rect",
    num: 4,
    score: 1,
    isBase: true,
    connections: [123],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t6",
  },
  {
    id: 125,
    prop: 0,
    typeText: "u",
    numText: "28",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [105, 106],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t6",
  },
  {
    id: 126,
    prop: 0,
    typeText: "u",
    numText: "29",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [124],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t6",
  },
  {
    id: 127,
    prop: 0,
    typeText: "u",
    numText: "30",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [124, 126],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t6",
  },
  {
    id: 128,
    prop: 0,
    typeText: "u",
    numText: "31",
    type: "circle",
    num: 1,
    score: 1,
    isBase: false,
    connections: [124, 126],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t6",
  },
  {
    id: 129,
    prop: 0,
    typeText: "u",
    numText: "32",
    type: "circle",
    num: 1,
    score: 0,
    isBase: false,
    connections: [124, 126],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t6",
  },
  {
    id: 130,
    prop: 0,
    typeText: "u",
    numText: "33",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [124, 99],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t6",
  },
  {
    id: 135,
    prop: 0,
    typeText: "u",
    numText: "34",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [123, 125, 126, 127, 130],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t6",
  },
  {
    id: 131,
    prop: 0,
    typeText: "u",
    numText: "35",
    type: "circle",
    num: 1,
    score: 0.6000000000000001,
    isBase: false,
    connections: [],
    secStart: true,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t7",
  },
  {
    id: 132,
    prop: 0,
    typeText: "u",
    numText: "36",
    type: "circle",
    num: 1,
    score: 0.6,
    isBase: false,
    connections: [131],
    secStart: false,
    secEnd: false,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: false,
    sectorName: "t7",
  },
  {
    id: 133,
    prop: 0,
    typeText: "u",
    numText: "37",
    type: "circle",
    num: 1,
    score: 0,
    isBase: false,
    connections: [132],
    secStart: false,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: true,
    arrowIn: false,
    level: 0,
    isLabel: true,
    secLength: 1,
    grey: true,
    sectorName: "t7",
  },
  {
    id: 134,
    prop: 0,
    typeText: "u",
    numText: "38",
    type: "roundrect",
    num: 1,
    score: 0,
    isBase: true,
    connections: [131, 132, 133],
    secStart: true,
    secEnd: true,
    fontStyle: "normal",
    arrowOut: false,
    arrowIn: true,
    level: 0,
    isLabel: true,
    secLength: 36,
    grey: true,
    sectorName: "t7",
  },
];
